### ISSUE TITLE
Fix snek5000/docs/examples/scripts/tuto_cbox.py

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000-cbox#32]
See https://github.com/snek5000/snek5000/issues/167#issuecomment-1313643227

I guess the issue  comes from snek5000-cbox. We need to understand what happens.

**Comment by akhoubani** [comment]
I noticed this problem: in the `.usr` file at line 282  `if (stretch_x.ne.0.0) then` should be `if (stretch_y.ne.0.0) then`. It means it does not stretch the mesh at all.

**Comment by paugier** [comment]
Does it fix the issue with the tuto script?

Anyway, it is much better to do a tiny commit with only this modif and to propose a PR with written in its description "Fixes #32" so that this issue would be closed automatically when the PR is merged.
