### ISSUE TITLE
src/snek5000_cbox/templates/SIZE.j2 with params.oper.L...

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000-cbox#35]
See https://github.com/snek5000/snek5000-cbox/pull/30#issuecomment-1313228182 and few comments after.

It would be much better to avoid copy pasting of https://github.com/snek5000/snek5000/blob/main/src/snek5000/resources/SIZE.j2 and to extend this file with jinja2 (See https://jinja.palletsprojects.com/en/3.0.x/templates/#template-inheritance).

Then, the parameters `u_oper_lx`, `u_oper_ly`, `u_oper_lz` can be used in `userbc` and `useric` subroutines to avoid `glmax`.

**Comment by ashwinvis** [comment]
Good idea on template inheritance. If I understood the docs, it needs upstream support with a block defined as.

```jinja
{% block user_size %} 
{% endblock %}
```

Other templates can also have such blocks to allow reusability.

**Comment by akhoubani** [comment]
> Good idea on template inheritance. If I understood the docs, it needs upstream support with a block defined as.
> 
> ```
> {% block user_size %} 
> {% endblock %}
> ```
> 
> Other templates can also have such blocks to allow reusability.

I don't know how I should proceed now. Should I extend and add this block in the snek, as you opened the issue  [snek5000/snek5000#200](https://github.com/snek5000/snek5000/issues/200)?

**Comment by paugier** [comment]
You can try to modify snek and to produce your own template from the snek template. You will need to learn how to use jinja2.

If it is actually too complicated, you can just for now copy-paste SIZE.j2 and modify it. It would be a good first step and we can use jinja2 inheritance later.
