### ISSUE TITLE
Save initial condition for movie

### ISSUE THREAD

**Issue by paugier** [snek5000/snek5000-cbox#41]
I tried https://github.com/snek5000/snek5000/issues/142#issuecomment-1318634416

but I get a strange compilation error:

```
   95 |       else if (istep .eq. 0 .and. (.not. chpt_ifrst)) then
      |                                        1
Error: Operand of .not. operator at (1) is REAL(8)
```

**Comment by ashwinvis** [comment]
Could you try adding `implicit none` (just before the include statements inside userchk) so we know it is not implicitly set as real.

**Comment by paugier** [comment]
Yes that was the problem. With `implicit none`, I get a much better error. And no error when `CHKPOINTD` is included.
